Repository jkutkutOrg/EatUp, pull requests merged in 2023-06, with the labels that each got.

#20 Dev setup add products
  .testing/Makefile
  db/load_db.sql
  db/public/products/desserts/brownie.jpg
  db/public/products/desserts/bun_roll_chocolate.jpg
  db/public/products/desserts/cake_caramel.jpg
  db/public/products/desserts/oreo_shake.jpg
  db/public/products/desserts/pancakes.jpg
  db/public/products/desserts/sweet_nachos.jpg
  db/public/products/drinks/beer.jpg
  db/public/products/drinks/coffee.jpg
  db/public/products/drinks/soft_drink.png
  db/public/products/drinks/tea.jpg
  db/public/products/drinks/wine.jpg
  db/public/products/main/benedict.jpg
  db/public/products/main/chic_chicken_bbq.jpg
  db/public/products/main/iberian_curry.png
  db/public/products/main/iberian_dam.png
  db/public/products/main/oriental_chicken.jpg
  db/public/products/main/soria_carbonara.png
  db/public/products/main/sticky_ribs.jpg
  db/public/products/main/vegan_burger.jpg
  db/public/products/main/wellington.png
  db/public/products/starters/bravas_potatoes.png
  db/public/products/starters/croquettes.png
  db/public/products/starters/green_power.jpg
  db/public/products/starters/onion_rings.png
  db/public/products/starters/quesadilla.png
  db/public/products/starters/rainbow_poke.jpg
Labels: enhancement, In progress

#23 Main readme
  readme.md
Labels: enhancement

#24 v1.0.0
  .testing/addOrder.js
  .testing/api/Eatup Server API.postman_collection.json
  .testing/api/environments/EatUp server.postman_environment.json
  .testing/api/environments/EatUp setup_server.postman_environment.json
  .testing/api/setup.postman_collection.json
  .testing/check_project_size.sh
  TODO.md
  setup/start.sh
Labels: documentation, enhancement
